services:
  api-service:
    environment:
      PYTHONPATH: /app/apps/api-service/src:/app/packages/visiox-common/src:/app/packages/visiox-paddlex/src
    volumes:
      - ../../apps/api-service/src:/app/apps/api-service/src
      - ../../packages/visiox-common/src:/app/packages/visiox-common/src
      - ../../packages/visiox-paddlex/src:/app/packages/visiox-paddlex/src
    command:
      - uvicorn
      - visiox_api.main:app
      - --host
      - 0.0.0.0
      - --port
      - "8000"
      - --reload
